stages:
  data_ingestion:
    cmd: python src/dataIngestion.py
    deps:
    - src/dataIngestion.py
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/dataPP.py
    deps:
    - data/raw
    - src/dataPP.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/featureEngine.py
    deps:
    - data/interim
    - src/featureEngine.py
    outs:
    - data/processed

  model_building:
    cmd: python src/modelTraining.py
    deps:
    - data/processed
    - src/modelTraining.py
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/modelEvaluation.py
    deps:
    - models/model.pkl
    - src/modelEvaluation.py
    metrics:
    - reports/metrics.json

# Removed:
# - Global params section
# - dvclive/params.yaml

metrics:
- dvclive/metrics.json

plots:
- dvclive/plots/metrics:
    x: step
